### ISSUE TITLE
make check fails: module.js version mismatch

### ISSUE THREAD

**Issue by rajanski** [strk/easycartodb#3]
Environment:

  ogr2ogr version: GDAL 1.11.0, released 2014/04/16

Running tests

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: Module version mismatch. Expected 11, got 1.
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/app/easycartodb/sql-api/node_modules/zipfile/lib/index.js:4:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/app/easycartodb/sql-api/test/acceptance/app.test.js:23:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /home/app/easycartodb/sql-api/node_modules/mocha/lib/mocha.js:157:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/app/easycartodb/sql-api/node_modules/mocha/lib/mocha.js:154:14)
    at Mocha.run (/home/app/easycartodb/sql-api/node_modules/mocha/lib/mocha.js:326:31)
    at Object.<anonymous> (/home/app/easycartodb/sql-api/node_modules/mocha/bin/_mocha:350:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
make[1]: **\* [check] Error 1
make[1]: Leaving directory `/home/app/easycartodb/sql-api'
make: **\* [check] Error 2

**Comment by strk** [comment]
Are you still running with node-0.8.9 ? If you pull again ./configure should now error out if you do.
Also, you'll have a "make clean" rule to run before "make" (or "make all") for forcing re-compilation of all modules.

**Comment by rajanski** [comment]
Hi no i have nodejs 0.10.26-1chl1~precise1

**Comment by strk** [comment]
Try pulling and then run "make clean all". If it still fails, please try with the upstream cartodb-sql-api and if "make" there fails please file the ticket there. Feel free to drop a reference to this ticket, so once it's fixed upstream this repo can point to the upstream fixed version.

**Comment by rajanski** [comment]
works now , but see https://github.com/strk/easycartodb/issues/4
